version: '3'
services:
  database:
    image: postgres:10
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS:--encoding=UTF-8 --locale=C
    restart: always

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    ports:
      - 8000:80
    volumes:
      -  tool-data:/var/lib/pgadmin
    environment:
      - TZ=Asia/Tokyo
      - PGADMIN_DEFAULT_EMAIL=admin@testdomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - database
    restart: always

  backend:
    image: openjdk:11
    container_name: backend
    hostname: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
      - ./work/.m2:/root/.m2
    working_dir: /app
    command:
      ./mvnw spring-boot:run
    depends_on:
      - database
#    tty: true

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    hostname: frontend
#    ports:
#      - "4200:4200"
#    volumes:
#      - "./frontend:/app"
#    working_dir: /app/node
##    command:
##      ng serve --host=0.0.0.0
#    depends_on:
#      - backend
#    tty: true

volumes:
  db-data:
    driver: local
  tool-data:
    driver: local
